# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0007_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=512)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evidence', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('diagnosed_by', models.CharField(choices=[('system', 'System'), ('agent', 'Agent')], default='system', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to='agreements.case')),
            ],
            options={
                'db_table': 'diagnosis_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
