# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
            options={
                'db_table': 'trust_score_logs',
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reliability', models.IntegerField(default=50)),
                ('dispute_rate_score', models.IntegerField(default=50)),
                ('account_age_score', models.IntegerField(default=50)),
                ('volume_score', models.IntegerField(default=50)),
                ('verification_score', models.IntegerField(default=50)),
                ('overall_score', models.IntegerField(default=50)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('disputed_transactions', models.IntegerField(default=0)),
                ('refunded_transactions', models.IntegerField(default=0)),
                ('score_history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_obj', to='merchants.merchant')),
            ],
            options={
                'db_table': 'trust_scores',
            },
        ),
    ]
