# Generated by Django 4.2.30 on 2026-07-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('event', models.CharField(choices=[('agreement.created', 'Agreement Created'), ('payment.pending', 'Payment Pending'), ('payment.collected', 'Payment Collected'), ('condition.met', 'Condition Met'), ('agreement.waiting', 'Agreement Waiting'), ('agreement.ready', 'Agreement Ready'), ('settlement.started', 'Settlement Started'), ('settlement.completed', 'Settlement Completed'), ('settlement.failed', 'Settlement Failed'), ('agreement.settled', 'Agreement Settled'), ('agreement.refunded', 'Agreement Refunded'), ('agreement.cancelled', 'Agreement Cancelled')], max_length=32)),
                ('channel', models.CharField(default='log', help_text='sms, email, webhook, push, log', max_length=32)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='agreements.agreement')),
            ],
            options={
                'db_table': 'notification_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
