# Generated by Django 5.0.6 on 2026-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='event',
            field=models.CharField(choices=[('agreement.created', 'Agreement Created'), ('payment.submitted', 'Payment Submitted'), ('payment.pending', 'Payment Pending'), ('payment.collected', 'Payment Collected'), ('payment.declined', 'Payment Declined'), ('condition.met', 'Condition Met'), ('agreement.held', 'Agreement Held'), ('agreement.ready', 'Agreement Ready'), ('agreement.disputed', 'Agreement Disputed'), ('settlement.started', 'Settlement Started'), ('settlement.completed', 'Settlement Completed'), ('settlement.failed', 'Settlement Failed'), ('agreement.settled', 'Agreement Settled'), ('agreement.reversed', 'Agreement Reversed'), ('agreement.refunded', 'Agreement Refunded'), ('agreement.cancelled', 'Agreement Cancelled')], max_length=32),
        ),
    ]
