# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('session_token', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('buyer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='merchants.merchant')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_deal', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'escrow_deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='escrow_deal_merchan_700779_idx'), models.Index(fields=['deal_code'], name='escrow_deal_deal_co_46c88d_idx'), models.Index(fields=['buyer_phone'], name='escrow_deal_buyer_p_6562bd_idx'), models.Index(fields=['created_at'], name='escrow_deal_created_79f09b_idx')],
            },
        ),
    ]
