# Generated by Django 4.2.30 on 2026-05-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowdeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('HELD', 'Held'), ('DELIVERED', 'Delivered'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
