# Generated by Django 5.2.5 on 2026-06-05 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_add_delivered_status'),
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='amount_released',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='b2c_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='b2c_conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='b2c_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='b2c_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='fee_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='ledger_status',
            field=models.CharField(choices=[('UNPAID', 'Buyer has not paid'), ('HELD', 'Funds in paybill, not yet released'), ('RELEASE_PENDING', 'B2C initiated, waiting for Safaricom'), ('RELEASED', 'Funds sent to seller'), ('STUCK', 'B2C failed, manual intervention needed')], default='UNPAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='escrowdeal',
            index=models.Index(fields=['b2c_conversation_id'], name='escrow_deal_b2c_con_05c2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowdeal',
            index=models.Index(fields=['ledger_status'], name='escrow_deal_ledger__69be5d_idx'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='escrow.escrowdeal'),
        ),
    ]
