# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0007_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_passed', models.BooleanField(default=False)),
                ('checks_total', models.IntegerField(default=0)),
                ('checks_passed', models.IntegerField(default=0)),
                ('recovery_confirmed', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='agreements.case')),
            ],
            options={
                'db_table': 'verification_results',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=128)),
                ('expected_value', models.JSONField(default=dict)),
                ('actual_value', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='agreements.case')),
            ],
            options={
                'db_table': 'verification_checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
