STATUS_CODES = {
    'OPEN': 10000,
    'INVESTIGATING': 20000,
    'RESOLVED': 30000,
    'CLOSED': 40000,
}

STATUS_CATEGORIES = {
    'OPEN': 'active',
    'INVESTIGATING': 'active',
    'RESOLVED': 'terminal',
    'CLOSED': 'terminal',
}

VALID_TRANSITIONS = {
    'OPEN': ['INVESTIGATING', 'CLOSED'],
    'INVESTIGATING': ['RESOLVED', 'CLOSED'],
    'RESOLVED': ['CLOSED'],
    'CLOSED': [],
}

TERMINAL_STATES = {'RESOLVED', 'CLOSED'}
