# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_by', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED_BUYER', 'Resolved — Buyer Wins'), ('RESOLVED_SELLER', 'Resolved — Seller Wins'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('buyer_evidence', models.TextField(blank=True)),
                ('seller_evidence', models.TextField(blank=True)),
                ('buyer_evidence_files', models.JSONField(blank=True, default=list)),
                ('seller_evidence_files', models.JSONField(blank=True, default=list)),
                ('resolution_notes', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_to', models.CharField(blank=True, max_length=10)),
                ('assigned_admin', models.CharField(blank=True, max_length=100)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='escrow.escrowdeal')),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
            ],
            options={
                'db_table': 'dispute_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
