# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('success_url', models.URLField(blank=True, max_length=500)),
                ('failure_url', models.URLField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_sessions', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_sessions',
                'indexes': [models.Index(fields=['session_token'], name='merchant_se_session_130f6e_idx'), models.Index(fields=['merchant', 'used'], name='merchant_se_merchan_61e39c_idx'), models.Index(fields=['expires_at'], name='merchant_se_expires_86e641_idx')],
            },
        ),
    ]
