# Generated by Django 4.2.30 on 2026-06-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsession',
            name='short_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='merchantsession',
            index=models.Index(fields=['short_code'], name='merchant_se_short_c_624d56_idx'),
        ),
    ]
