# Generated by Django 4.2.30 on 2026-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('display_name', models.CharField(default='Operator', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=64)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, default='', max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'admin_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('backup_type', models.CharField(default='manual', max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_platform_settings',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'admin_login_attempt',
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='admin_login_ip_addr_32ba7f_idx')],
            },
        ),
    ]
