# Generated by Django 5.0.6 on 2026-07-09 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('alert_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('message', models.TextField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notified_via_email', models.BooleanField(default=False)),
                ('notified_via_sms', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_security_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='admin_dashboard.adminuser'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=16),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
