# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0007_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_adapter', models.CharField(max_length=128)),
                ('query_type', models.CharField(max_length=128)),
                ('raw_response', models.JSONField(default=dict)),
                ('assembled_context', models.JSONField(default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_records', to='agreements.case')),
            ],
            options={
                'db_table': 'context_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
