# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=128)),
                ('parameters', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('approved_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'action_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=16)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='action_engine.actionplan')),
            ],
            options={
                'db_table': 'action_results',
                'ordering': ['-executed_at'],
            },
        ),
    ]
