# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0007_case'),
        ('action_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='agreements.case'),
        ),
    ]
