from django.db import models

class Agreement(models.Model):
    class Status(models.TextChoices):
        CREATED = 'CREATED', 'Created'
        PAYMENT_PENDING = 'PAYMENT_PENDING', 'Payment Pending'
        COLLECTED = 'COLLECTED', 'Collected'
        WAITING = 'WAITING', 'Waiting'
        READY = 'READY', 'Ready'
        SETTLING = 'SETTLING', 'Settling'
        SETTLED = 'SETTLED', 'Settled'
        REFUNDED = 'REFUNDED', 'Refunded'
        CANCELLED = 'CANCELLED', 'Cancelled'

    agreement_id = models.CharField(max_length=24, unique=True, editable=False)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.CREATED)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default='KES')
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    creator_id = models.CharField(max_length=255, help_text="User or org that created this")
    creator_type = models.CharField(max_length=32, default='organization')

    payment_url = models.URLField(blank=True, default='', help_text="Checkout link generated by payment provider")
    developer_webhook_url = models.URLField(blank=True, default='', help_text="Outgoing webhook URL for developer notifications")

    class Meta:
        db_table = 'agreements'
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.agreement_id:
            import secrets, string
            self.agreement_id = 'AGR' + ''.join(secrets.choice(string.ascii_uppercase + string.digits) for _ in range(16))
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.agreement_id} [{self.status}] {self.title}"


class AgreementParty(models.Model):
    class Role(models.TextChoices):
        PAYER = 'PAYER', 'Payer'
        PAYEE = 'PAYEE', 'Payee'
        PLATFORM = 'PLATFORM', 'Platform'
        PARTNER = 'PARTNER', 'Partner'
        AGENT = 'AGENT', 'Agent'

    agreement = models.ForeignKey(Agreement, on_delete=models.CASCADE, related_name='parties')
    role = models.CharField(max_length=16, choices=Role.choices)
    identifier = models.CharField(max_length=128, help_text='Email, phone, or org ID')
    name = models.CharField(max_length=255)
    payout_method = models.CharField(max_length=32, blank=True, default='')
    payout_details = models.JSONField(default=dict, blank=True)
    split_percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    split_fixed = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'agreement_parties'

    def __str__(self):
        return f"{self.agreement.agreement_id} {self.role} {self.name}"