# Generated by Django 4.2.30 on 2026-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='hash',
            field=models.CharField(blank=True, help_text='SHA-256 of this entry', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of previous ledger entry', max_length=64),
        ),
    ]
