# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_case'),
        ('ledger', '0002_ledgerentry_hash_ledgerentry_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='agreements.case'),
        ),
    ]
