# Generated by Django 4.2.30 on 2026-07-09 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('industry', models.CharField(blank=True, default='', max_length=64)),
                ('admin_name', models.CharField(blank=True, default='', max_length=128)),
                ('admin_phone', models.CharField(blank=True, default='', max_length=32)),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('api_key', models.CharField(blank=True, max_length=128, unique=True)),
                ('api_key_masked', models.CharField(blank=True, default='', max_length=64)),
                ('split_default', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer_tenant',
            },
        ),
    ]
