# Generated by Django 4.2.30 on 2026-07-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('COLLECTED', 'Collected'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('SETTLING', 'Settling'), ('SETTLED', 'Settled'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(help_text='User or org that created this', max_length=255)),
                ('creator_type', models.CharField(default='organization', max_length=32)),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PAYER', 'Payer'), ('PAYEE', 'Payee'), ('PLATFORM', 'Platform'), ('PARTNER', 'Partner'), ('AGENT', 'Agent')], max_length=16)),
                ('identifier', models.CharField(help_text='Email, phone, or org ID', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('payout_method', models.CharField(blank=True, default='', max_length=32)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('split_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('split_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='agreements.agreement')),
            ],
            options={
                'db_table': 'agreement_parties',
            },
        ),
    ]
