# Generated by Django 4.2.30 on 2026-09-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_column='agreement_id', editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('status_code_value', models.IntegerField(db_index=True, default=10000)),
                ('txn_id', models.CharField(blank=True, default='', help_text='Transaction reference number', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='', help_text='Screenshot or evidence URL')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('assigned_team', models.CharField(default='FRAUD_TEAM', max_length=100)),
                ('resolution', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100)),
                ('severity', models.CharField(default='NORMAL', help_text='LOW, NORMAL, HIGH, CRITICAL', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('triggered_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='agreements.case')),
            ],
            options={
                'db_table': 'case_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='Name or role of sender', max_length=100)),
                ('sender_type', models.CharField(default='customer', help_text='customer, agent, system', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agreements.case')),
            ],
            options={
                'db_table': 'case_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(default='screenshot', help_text='screenshot, document, statement, other', max_length=50)),
                ('url', models.URLField(blank=True, default='')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_by', models.CharField(default='customer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='agreements.case')),
            ],
            options={
                'db_table': 'case_evidence',
                'ordering': ['-created_at'],
            },
        ),
    ]
