# Generated by Django 4.2.30 on 2026-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='developer_webhook_url',
            field=models.URLField(blank=True, default='', help_text='Outgoing webhook URL for developer notifications'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='payment_url',
            field=models.URLField(blank=True, default='', help_text='Checkout link generated by payment provider'),
        ),
    ]
