# Generated by Django 5.0.6 on 2026-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_developer_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('RECONCILING', 'Reconciling'), ('HELD', 'Held'), ('DISPUTED', 'Disputed'), ('READY', 'Ready'), ('SETTLING', 'Settling'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('DECLINED', 'Declined'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('FAILED_PERMANENT', 'Failed Permanent'), ('PAYMENT_PENDING', 'Payment Pending (legacy)'), ('COLLECTED', 'Collected (legacy)'), ('WAITING', 'Waiting (legacy)')], default='CREATED', max_length=20),
        ),
    ]
