# Generated by Django 4.2.30 on 2026-07-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_migrate_old_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING_KYC', 'Pending KYC'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('RECONCILING', 'Reconciling'), ('HELD', 'Held'), ('DISPUTED', 'Disputed'), ('READY', 'Ready'), ('SETTLING', 'Settling'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('DECLINED', 'Declined'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('FAILED_PERMANENT', 'Failed Permanent'), ('PAYMENT_PENDING', 'Payment Pending (legacy)'), ('COLLECTED', 'Collected (legacy)'), ('WAITING', 'Waiting (legacy)')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='agreementparty',
            name='role',
            field=models.CharField(db_index=True, help_text='Party role: BUYER, SELLER, VENDOR, DELIVERY_AGENT, MARKETPLACE, CUSTOMER, PLATFORM, PAYER, PAYEE, PARTNER, AGENT', max_length=32),
        ),
    ]
