# Generated by Django 4.2.30 on 2026-07-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_alter_agreement_status_alter_agreementparty_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='status_code_value',
            field=models.IntegerField(db_index=True, default=10000, help_text='Numeric status code for fast range queries'),
        ),
    ]
