# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_agreement_status_code_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_column='agreement_id', editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING_KYC', 'Pending KYC'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('RECONCILING', 'Reconciling'), ('HELD', 'Held'), ('DISPUTED', 'Disputed'), ('READY', 'Ready'), ('SETTLING', 'Settling'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('SETTLED', 'Settled'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('DECLINED', 'Declined'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('FAILED_PERMANENT', 'Failed Permanent'), ('PAYMENT_PENDING', 'Payment Pending (legacy)'), ('COLLECTED', 'Collected (legacy)'), ('WAITING', 'Waiting (legacy)')], default='CREATED', max_length=20)),
                ('status_code_value', models.IntegerField(db_index=True, default=10000, help_text='Numeric status code for fast range queries')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.CharField(help_text='User or org that created this', max_length=255)),
                ('creator_type', models.CharField(default='organization', max_length=32)),
                ('payment_url', models.URLField(blank=True, default='', help_text='Checkout link generated by payment provider')),
                ('developer_webhook_url', models.URLField(blank=True, default='', help_text='Outgoing webhook URL for developer notifications')),
            ],
            options={
                'db_table': 'agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
