# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_alter_settlement_agreement_alter_settlement_provider'),
        ('notifications', '0003_alter_notificationevent_agreement'),
        ('ledger', '0003_alter_ledgerentry_agreement'),
        ('agreements', '0007_case'),
        ('conditions', '0002_alter_condition_agreement'),
        ('state_machine', '0004_alter_statetransition_agreement_and_more'),
        ('payments', '0002_alter_paymenttransaction_agreement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
        migrations.RenameModel(
            old_name='AgreementParty',
            new_name='CaseParty',
        ),
        migrations.AlterField(
            model_name='caseparty',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='agreements.case'),
        ),
    ]
