# Generated by Django 4.2.30 on 2026-09-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_id'),
        ('agreements', '0008_delete_agreement_rename_agreementparty_caseparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='channel',
            field=models.CharField(blank=True, default='API', help_text='Entry channel: WEB, MOBILE, API, VOICE, SMS, WIDGET', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_ref',
            field=models.CharField(blank=True, default='', help_text='Organization internal customer reference', max_length=128),
        ),
        migrations.AddField(
            model_name='case',
            name='intent',
            field=models.CharField(blank=True, default='', help_text='Case type: FRAUD_REPORT, DATA_FAILURE, ORDER_NOT_RECEIVED, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='severity',
            field=models.CharField(default='NORMAL', help_text='LOW, NORMAL, HIGH, CRITICAL', max_length=20),
        ),
    ]
