# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0007_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(max_length=128)),
                ('conditions', models.JSONField(default=dict)),
                ('required_clearance', models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='L1', max_length=8)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('escalated', 'Escalated')], default='approved', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('decided_by', models.CharField(max_length=128)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to='agreements.case')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='policy_engine.policyrule')),
            ],
            options={
                'db_table': 'policy_decisions',
                'ordering': ['-decided_at'],
            },
        ),
    ]
