# Generated by Django 4.2.30 on 2026-07-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('provider', models.CharField(choices=[('mpesa_b2c', 'M-Pesa B2C'), ('bank_transfer', 'Bank Transfer'), ('intasend', 'IntaSend'), ('stripe', 'Stripe')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=10)),
                ('provider_tx_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='agreements.agreement')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='agreements.agreementparty')),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
