# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_case'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='agreements.case'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='provider',
            field=models.CharField(choices=[('mpesa_b2c', 'M-Pesa B2C'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe')], max_length=16),
        ),
    ]
