# Generated by Django 4.2.30 on 2026-07-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('condition_type', models.CharField(choices=[('buyer_confirmation', 'Buyer Confirmation'), ('seller_confirmation', 'Seller Confirmation'), ('timeout', 'Timeout'), ('document_uploaded', 'Document Uploaded'), ('inspection', 'Inspection Passed'), ('admin_approval', 'Admin Approval'), ('custom_webhook', 'Custom Webhook'), ('payment_received', 'Payment Received')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('label', models.CharField(help_text='Human-readable description', max_length=255)),
                ('required', models.BooleanField(default=True, help_text='Must be met for READY transition')),
                ('order', models.IntegerField(default=0, help_text='Evaluation order')),
                ('timeout_hours', models.IntegerField(blank=True, help_text='Auto-fail after N hours', null=True)),
                ('timeout_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('met_by', models.CharField(blank=True, default='', help_text='Who/What triggered this', max_length=128)),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='agreements.agreement')),
            ],
            options={
                'db_table': 'conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
