# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_case'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='agreements.case'),
        ),
    ]
