# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa Daraja'), ('pesapal', 'Pesapal'), ('equity', 'Equity Bank'), ('card', 'Card Payment')], default='mpesa', max_length=20)),
                ('provider_tx_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('mpesa_receipt', models.CharField(blank=True, db_index=True, max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('deal_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='merchants.merchant')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['merchant', 'status'], name='payment_tra_merchan_4e1423_idx'), models.Index(fields=['checkout_request_id'], name='payment_tra_checkou_b679ef_idx'), models.Index(fields=['mpesa_receipt'], name='payment_tra_mpesa_r_9efecb_idx'), models.Index(fields=['deal_code'], name='payment_tra_deal_co_593d2b_idx')],
            },
        ),
    ]
