# Generated by Django 4.2.30 on 2026-07-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0002_agreement_developer_webhook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('raw_body', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('provider', models.CharField(help_text='intasend, mpesa, stripe', max_length=32)),
                ('provider_tx_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(default='pending', help_text='pending, completed, failed', max_length=16)),
                ('reference', models.CharField(blank=True, default='', help_text='Internal reference (agreement_id)', max_length=128)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='agreements.agreement')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
