# Generated by Django 4.2.30 on 2026-09-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('status_code', models.IntegerField(blank=True, help_text='Numeric code for the target state', null=True)),
                ('triggered_by', models.CharField(help_text='Who triggered this (name/username)', max_length=128)),
                ('actor_id', models.CharField(blank=True, default='', help_text='Specific identifier of the actor (user ID, system ID, provider agent ID)', max_length=128)),
                ('actor_role', models.CharField(blank=True, default='', help_text='Role of the actor: system, admin, customer, provider_webhook, vendor, buyer, delivery_agent', max_length=32)),
                ('channel', models.CharField(blank=True, default='', help_text='Channel: api, webhook, admin_dashboard, portal, system, sms, email', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('provider_ref', models.CharField(blank=True, default='', help_text='Payment provider reference (M-Pesa txn ID, Stripe PI)', max_length=256)),
                ('trigger_reason', models.CharField(blank=True, default='', help_text='Short machine-readable reason code for the transition', max_length=512)),
                ('reason', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting data (receipt, doc ref, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='agreements.case')),
            ],
            options={
                'db_table': 'state_transitions',
                'ordering': ['created_at'],
            },
        ),
    ]
