# Generated by Django 4.2.30 on 2026-07-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('triggered_by', models.CharField(help_text='Who triggered this', max_length=128)),
                ('reason', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Supporting data (receipt, doc ref, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='agreements.agreement')),
            ],
            options={
                'db_table': 'state_transitions',
                'ordering': ['created_at'],
            },
        ),
    ]
