# Generated by Django 5.0.6 on 2026-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransition',
            name='actor_role',
            field=models.CharField(blank=True, default='', help_text='Role of the actor: system, admin, customer, provider_webhook', max_length=32),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='channel',
            field=models.CharField(blank=True, default='', help_text='Channel: api, webhook, admin_dashboard, portal, system', max_length=32),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='Numeric code for the target state', null=True),
        ),
    ]
