# Generated by Django 4.2.30 on 2026-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_machine', '0002_statetransition_actor_role_statetransition_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransition',
            name='actor_id',
            field=models.CharField(blank=True, default='', help_text='Specific identifier of the actor (user ID, system ID, provider agent ID)', max_length=128),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='provider_ref',
            field=models.CharField(blank=True, default='', help_text='Payment provider reference (M-Pesa txn ID, IntaSend ID, Stripe PI)', max_length=256),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='trigger_reason',
            field=models.CharField(blank=True, default='', help_text='Short machine-readable reason code for the transition', max_length=512),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='actor_role',
            field=models.CharField(blank=True, default='', help_text='Role of the actor: system, admin, customer, provider_webhook, vendor, buyer, delivery_agent', max_length=32),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='channel',
            field=models.CharField(blank=True, default='', help_text='Channel: api, webhook, admin_dashboard, portal, system, sms, email', max_length=32),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='triggered_by',
            field=models.CharField(help_text='Who triggered this (name/username)', max_length=128),
        ),
    ]
