# Generated by Django 4.2.30 on 2026-09-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_case'),
        ('state_machine', '0003_statetransition_actor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statetransition',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='agreements.case'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='provider_ref',
            field=models.CharField(blank=True, default='', help_text='Payment provider reference (M-Pesa txn ID, Stripe PI)', max_length=256),
        ),
    ]
