# Generated by Django 4.2.30 on 2026-05-12 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('merchant_key', models.CharField(max_length=255, unique=True)),
                ('api_key_hash', models.CharField(max_length=255)),
                ('api_secret_hash', models.CharField(max_length=255)),
                ('secret_version', models.IntegerField(default=1)),
                ('secret_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('success_url', models.URLField(blank=True, max_length=500)),
                ('failure_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('compliance_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_documents', models.JSONField(blank=True, default=dict)),
                ('monthly_volume_limit', models.DecimalField(decimal_places=2, default=100000.0, max_digits=15)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dispute_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='MerchantAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=255)),
                ('secret_hash', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchant_api_keys',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['merchant_key'], name='merchants_merchan_d98fff_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['email'], name='merchants_email_fc58cd_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['compliance_status'], name='merchants_complia_c97fb0_idx'),
        ),
    ]
