# Generated by Django 4.2.30 on 2026-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
