# Generated by Django 5.2.5 on 2026-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_add_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='payout_account',
            field=models.CharField(blank=True, help_text='Phone number for B2C, till number, or bank account', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='payout_account_name',
            field=models.CharField(blank=True, help_text='Account holder name (required if method=bank)', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='payout_bank_name',
            field=models.CharField(blank=True, help_text='Bank name (required if method=bank)', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='payout_method',
            field=models.CharField(choices=[('phone', 'Phone (M-Pesa B2C)'), ('pochi', 'Pochi la Biashara'), ('till', 'Till Number (Coming Soon)'), ('bank', 'Bank Transfer (Coming Soon)')], default='phone', max_length=20),
        ),
    ]
