# Generated by Django 4.2.30 on 2026-07-01 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_payout_account_merchant_payout_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='Business contact / M-Pesa receiving number', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('business_reg_number', models.CharField(blank=True, help_text='Certificate of registration', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
                ('settlement_preference', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('instant', 'Instant')], default='instant', max_length=10)),
                ('cashier_pin', models.CharField(blank=True, help_text='6-digit PIN for cashier login', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kra_pin', models.CharField(blank=True, help_text='KRA PIN for tax compliance', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='merchants.merchant')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_entered', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='merchants.business')),
            ],
            options={
                'db_table': 'cashier_sessions',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='merchants.organization'),
        ),
    ]
