# Generated by Django 4.2.30 on 2026-07-01 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_business_organization_cashiersession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('insurance', 'Insurance Company'), ('event', 'Event Organiser'), ('franchise', 'Franchise'), ('school', 'School / Education'), ('clinic', 'Clinic / Hospital'), ('laundry', 'Laundry / Cleaning'), ('retail', 'Retail / Shop'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='E.g. "Platform fee", "Partner share"', max_length=255)),
                ('split_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 5.00) or fixed amount (KES)', max_digits=8)),
                ('destination_account', models.CharField(blank=True, help_text='Where this split goes (wallet phone, bank ref, or "platform")', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority processed first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to='merchants.organization')),
            ],
            options={
                'db_table': 'split_rules',
                'ordering': ['-priority'],
            },
        ),
    ]
