# Generated by Django 4.2.16 on 2026-09-15 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('org_type', models.CharField(choices=[('BANK', 'Bank'), ('TELCO', 'Telco'), ('ECOMMERCE', 'E-Commerce'), ('INSURANCE', 'Insurance'), ('UTILITY', 'Utility'), ('SACCO', 'SACCO'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('integration_mode', models.CharField(choices=[('EMBEDDED', 'Embedded (Widget/Deep Link)'), ('STANDALONE', 'Standalone (TrustLayer Portal)'), ('API', 'API Only')], default='EMBEDDED', max_length=20)),
                ('brand_color', models.CharField(default='#FF5522', max_length=7)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('webhook_url', models.URLField(blank=True, default='', help_text='POST case updates here')),
                ('api_key', models.CharField(blank=True, default='', help_text='Partner API key for authentication', max_length=128)),
                ('supported_intents', models.JSONField(blank=True, default=list, help_text='Case types this org supports')),
                ('supported_channels', models.JSONField(blank=True, default=list, help_text='Entry channels: WEB, MOBILE, API, VOICE, SMS, WIDGET')),
                ('mcc_mnc', models.JSONField(blank=True, default=list, help_text='MCC/MNC codes e.g. ["63902"] for Safaricom Kenya')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
